name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: git clone https://github.com/VikkyAblaeva/hexlet-study.git
          make say-hello
